// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2WQAyMr4r-drxbPJ8UuHnZOdfue07YY',
    appId: '1:63064187738:web:0ff1964374aa21f857c963',
    messagingSenderId: '63064187738',
    projectId: 'saiph-1de28',
    authDomain: 'saiph-1de28.firebaseapp.com',
    storageBucket: 'saiph-1de28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFNtoffcpaq3fnTPJBKmVqgfnBTLtCFw',
    appId: '1:63064187738:android:aba1985f3135730057c963',
    messagingSenderId: '63064187738',
    projectId: 'saiph-1de28',
    storageBucket: 'saiph-1de28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3GRfUG8xWRbdO7aVoqazAorkfR0Wj_Yc',
    appId: '1:63064187738:ios:e78a60c9888d122c57c963',
    messagingSenderId: '63064187738',
    projectId: 'saiph-1de28',
    storageBucket: 'saiph-1de28.firebasestorage.app',
    iosBundleId: 'com.example.dumcapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3GRfUG8xWRbdO7aVoqazAorkfR0Wj_Yc',
    appId: '1:63064187738:ios:e78a60c9888d122c57c963',
    messagingSenderId: '63064187738',
    projectId: 'saiph-1de28',
    storageBucket: 'saiph-1de28.firebasestorage.app',
    iosBundleId: 'com.example.dumcapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL2WQAyMr4r-drxbPJ8UuHnZOdfue07YY',
    appId: '1:63064187738:web:10f67e594543d06b57c963',
    messagingSenderId: '63064187738',
    projectId: 'saiph-1de28',
    authDomain: 'saiph-1de28.firebaseapp.com',
    storageBucket: 'saiph-1de28.firebasestorage.app',
  );
}
